### PR TITLE
Add Postman collection 

### PR DESCRIPTION
**Pull request by manedev79**
to simplify smoke testing with default test rest resources. See #2

### CODE REVIEW

**Comment by JanLoebel** [comment]
So far so good :) Thank you! But don't we have to specify also the expected response in any way? Or is this a step which is not done in Postman?

**Comment by manedev79** [comment]
Sure, we can add some expectations. So far it only checks that there are no
error responses.
I will add some expectations.

Jan Löbel <notifications@github.com> schrieb am Do., 11. Okt. 2018, 13:10:

**Comment by JanLoebel** [comment]
Awesome :)

**Comment by manedev79** [comment]
Added some expectations. Done from my side. Let me know what you think.

**Comment by JanLoebel** [comment]
Awesome, thank you :)

**Pull request merged**
